### ISSUE TITLE
Connection error since 0.8.0

### ISSUE THREAD

**Issue by frots** [giraffi/fluent-plugin-amqp#21]
Hi,

When using the 0.8.0 version of this gem with td-agent, I am not able to connect to my RabbitMQ servers anymore. The following error is reported:
```
2016-05-02 12:35:42 +0000 [info]: Connecting to RabbitMQ...
2016-05-02 12:35:42 +0000 [error]: unexpected error error_class=TypeError error=#<TypeError: no implicit conversion of String into Integer>
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-amqp-0.8.0/lib/fluent/plugin/out_amqp.rb:115:in `initialize'
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-amqp-0.8.0/lib/fluent/plugin/out_amqp.rb:115:in `new'
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-amqp-0.8.0/lib/fluent/plugin/out_amqp.rb:115:in `get_connection_options'
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-amqp-0.8.0/lib/fluent/plugin/out_amqp.rb:57:in `start'
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/agent.rb:67:in `block in start'
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/agent.rb:66:in `each'
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/agent.rb:66:in `start'
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/root_agent.rb:104:in `start'
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/engine.rb:225:in `start'
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/engine.rb:175:in `run'
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/supervisor.rb:597:in `run_engine'
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/supervisor.rb:148:in `block in start'
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/supervisor.rb:352:in `call'
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/supervisor.rb:352:in `main_process'
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/supervisor.rb:325:in `block in supervise'
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/supervisor.rb:324:in `fork'
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/supervisor.rb:324:in `supervise'
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/supervisor.rb:142:in `start'
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/command/fluentd.rb:171:in `<top (required)>'
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/bin/fluentd:6:in `<top (required)>'
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2016-05-02 12:35:42 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
  2016-05-02 12:35:42 +0000 [error]: /usr/sbin/td-agent:7:in `load'
  2016-05-02 12:35:42 +0000 [error]: /usr/sbin/td-agent:7:in `<main>'
2016-05-02 12:35:42 +0000 [info]: shutting down fluentd
2016-05-02 12:35:42 +0000 [info]: shutting down output type="null" plugin_id="object:145bcac"
2016-05-02 12:35:42 +0000 [info]: process finished code=0
2016-05-02 12:35:42 +0000 [warn]: process died within 1 second. exit.
```

**Comment by sawanoboly** [comment]
Could you please show us your configuration(without security credentials) ?

**Comment by sawanoboly** [comment]
Ah, I found wrong usage of Array at `Array.new(@host)`. I'll fix soon.

**Comment by sawanoboly** [comment]
@frots Please check v0.8.1.

**Comment by frots** [comment]
Hi @sawanoboly,

Thanks for the quick reply (and fix). I'll test it asap and will let you know.
