### ISSUE TITLE
Plugin crash on FluentD 0.14.5 due to uninitialised constant error

### ISSUE THREAD

**Issue by warmfusion** [giraffi/fluent-plugin-amqp#28]
## Installed Gems

```
*** LOCAL GEMS ***

amq-protocol (1.9.2)
bigdecimal (1.2.4)
bunny (2.0.0.rc2)
cool.io (1.4.5)
daemons (1.2.4)
fluent-plugin-amqp (0.9.1, 0.9.0)
fluentd (0.14.5)
hiera (1.3.4)
http_parser.rb (0.6.0)
io-console (0.4.2)
json (2.0.2, 1.8.1)
minitest (4.7.5)
mixlib-cli (1.5.0)
msgpack (1.0.0)
psych (2.0.5)
rake (10.1.0)
rdoc (4.1.0)
ruby-shadow (2.3.4)
sensu-plugin (1.1.0)
serverengine (2.0.0)
sigdump (0.2.4)
stomp (1.4.3)
strptime (0.1.8)
sys-proctable (1.1.1 universal-linux)
systemu (2.6.5)
test-unit (2.1.5.0)
thread_safe (0.3.5)
tzinfo (1.2.2)
tzinfo-data (1.2016.6)
yajl-ruby (1.2.1)
```

## Stack Trace
```
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: unexpected error error="uninitialized constant Fluent::Plugin::MultilineParser"
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/plugin/in_tail.rb:88:in `configure'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/root_agent.rb:237:in `add_source'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/root_agent.rb:95:in `block in configure'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/root_agent.rb:92:in `each'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/root_agent.rb:92:in `configure'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/engine.rb:119:in `configure'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/engine.rb:93:in `run_configure'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/supervisor.rb:673:in `run_configure'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/supervisor.rb:435:in `block in run_worker'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/supervisor.rb:606:in `call'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/supervisor.rb:606:in `main_process'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/supervisor.rb:431:in `run_worker'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/lib/fluent/command/fluentd.rb:271:in `<top (required)>'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Sep 07 11:10:59 myserver fluentd[4900]: 2016-09-07 11:10:59 +0000 [error]: /var/lib/gems/2.1.0/gems/fluentd-0.14.5/bin/fluentd:5:in `<top (required)>'
```

**Comment by warmfusion** [comment]
This might infact be an upstream bug based on the stack trace... investigating further

**Comment by warmfusion** [comment]
Confirmed - https://github.com/fluent/fluentd/issues/1213

**Comment by warmfusion** [comment]
I'm wondering - should we exclude 0.14.5 from the gemspec now as we know that upstream is broken?
